name: Version

on:
  push:
    branches:
      - main

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - uses: actions/setup-node@v7
        with:
          node-version: 26
          registry-url: https://registry.npmjs.org
      - run: npm install
      - uses: changesets/action@v2
        with:
          publish-script: ./release.sh
          github-token: ${{secrets.GITHUB_TOKEN}}
        env:
          OVSX_PAT: ${{secrets.OPEN_VSX_TOKEN}}
          VSCE_PAT: ${{secrets.VSCE_TOKEN}}
